site_name: Cours NSI
site_url: https://nxpat.github.io/nsi/

theme:
  name: pyodide-mkdocs-theme
  language: fr
  icon:
    logo: material/code-block-tags
  favicon: assets/mdi--code-block-tags
  features:
    - navigation.tabs
    - navigation.tabs.sticky



extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details      # Enables the ??? collapsible accordion syntax
  - pymdownx.superfences  # Enables nesting code blocks & macros inside accordions
  - md_in_html       # Tells MkDocs to read Markdown inside HTML elements
  - attr_list        # Allows custom CSS attributes (used heavily by the theme)
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Accueil: index.md
  - Première:
    - 1. Commencer à programmer: 
        - Introduction au langage Python: premiere/01_intro_python.ipynb
    - 2. Systèmes et périphériques:
        - Commandes Unix: premiere/02_unix_commands.md
        - Historique d'Unix: premiere/02_unix_history.md
  - Terminale:
    - Sommaire: terminale/sommaire.md
    - 1. Structurer les données: terminale/01_tad.md
    - 2. Programmation Orientée Objet: terminale/02_poo.md
    - 3. Programmer en grand: terminale/03_peg.md
    - 4. SGBD Relationnels et SQL: terminale/04_sql.md
    - 5. Routage et réseaux: terminale/05_networks.md
    - 6. Système sur puce - SoC: terminale/06_soc.md
    - 7. Récursivité: 
        - terminale/07_rec.md
        - terminale/07__exp_rapide.md
        - terminale/07__arbre_dappel.md
        - terminale/07__tour_hanoi.md
    - 8. Arbres:
        - terminale/08_arbres.md
        - terminale/08__abr.md
        - terminale/08__abr_insert.md
        - terminale/08__abr_del.md
        - terminale/08__parcours_infixe.md
    - 9. Graphes:
        - terminale/09_graphes.md
        - terminale/09__densite.md
        - terminale/09__parcours_bfs.md
        - terminale/09__parcours_dfs.md
        - terminale/09__cycles.md
        - terminale/09__dijkstra.md
        - terminale/09__best_first_search.md
        - terminale/09__algo_a.md
        - terminale/09__heuristique.md

plugins:
  - search
  - mkdocs-jupyter
  - pyodide_macros:
      project:
        id: "cours_nsi_terminale"
      playground: 
        include: "none"   # Hide with "none" or display with "site"
      testing:
        include: "serve"  # Display on dev server