name: Deploy MkDocs
on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Dependencies
        run: pip install pyodide-mkdocs-theme

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force